const dashboardLocators = {
    dashboard_title: "h4.font-weight-700",
    profile_photo: ".avatar-rounded",
    language_icon: '[alt="lang-flag"]',
    armenian_changed_assertion: 'Գլխավոր',
    russian_changed_assertion: 'Главная',
    pending_drivers_section: 'Pending Drivers',
    active_drivers_section: 'Active Drivers',
    other_drivers_section: 'Rejected / Banned Drivers',
    rider_section: '[href="#rider"]',
    rider_page: 'Rider List',
    all_ride_requests_page: 'All List',
    new_ride_requests_page: 'New Ride List',
    completed_ride_requests_page: 'Completed List',
    missed_ride_requests_page: 'Missed List',
    cancelled_ride_requests_page: 'cancelled List',
    pending_ride_requests_page: 'Pending List',
    ride_report_page: 'Ride Report',
    earnings_report_page: 'Earnings Report',
    top_up_report_page: 'Driver Top-Up Report',
    tax_report_page: 'Ride Tax Service Report',
    truck_tax_report_page: 'Truck/Tow Truck Tax Service Report',
    driver_section: '[href="#driver"]',
    collapsed_menu: "i.wrapper-menu",
    service_section: '[href="#service"]',
    add_service_page: 'Add Service',
    support_chat_section: '[href="#support"]',
    ride_requests_section: '[href="#riderequest"]',
    report_section: '[href="#report"]',
    room_list_page: 'Room List',
}

const dashboardConstants = {
    dashboard_url: "https://admin.apexcab.net/home",
    armenian_language: "Armenian",
    russian_language: "Russian",
    english_language: "English",
}

export {dashboardLocators, dashboardConstants}